labelall={	"person":"บุคคล",
	"bicycle":"จักรยาน",
	"car":"รถ",
	"motorcycle":"รถจักรยานยนต์",
	"airplane":"เครื่องบิน",
	"bus":"รสบัส",
	"train":"รถไฟ",
	"truck":"รถบรรทุก",
	"boat":"เรือ",
	"traffic light":"ไฟจราจร",
	"fire hydrant":"ดับเพลิง",
	"???":"-",
	"stop sign":"ป้ายหยุด",
	"parking meter":"มิเตอร์จอดรถ",
	"bench":"ม้านั่ง",
	"bird":"นก",
	"cat":"แมว",
	"dog":"สุนัข",
	"horse":"ม้า",
	"sheep":"แกะ",
	"cow":"วัว",
	"elephant":"ช้าง",
	"bear":"หมี",
	"zebra":"ม้าลาย",
	"giraffe":"ยีราฟ",
	"???":"-",
	"backpack":"กระเป๋าเป้สะพายหลัง",
	"umbrella":"ร่ม",
	"???":"-",
	"???":"-",
	"handbag":"กระเป๋าถือ",
	"tie":"ผูก",
	"suitcase":"กระเป๋าเดินทาง",
	"frisbee":"จานร่อน",
	"skis":"สกี",
	"snowboard":"สโนว์บอร์ด",
	"sports ball":"ลูกบอลกีฬา",
	"kite":"ว่าว",
	"baseball bat":"ไม้เบสบอล",
	"baseball glove":"ถุงมือเบสบอล",
	"skateboard":"สเก็ตบอร์ด",
	"surfboard":"กระดานโต้คลื่น",
	"tennis racket":"ไม้เทนนิส",
	"bottle":"ขวด",
	"???":"-",
	"wine glass":"แก้วไวน์",
	"cup":"ถ้วย",
	"fork":"ส้อม",
	"knife":"มีด",
	"spoon":"ช้อน",
	"bowl":"ชาม",
	"banana":"กล้วย",
	"apple":"แอปเปิล",
	"sandwich":"แซนด์วิช",
	"orange":"ส้ม",
	"broccoli":"บร็อคโคลี",
	"carrot":"แครอท",
	"hot dog":"ฮอทดอก",
	"pizza":"พิซซ่า",
	"donut":"โดนัท",
	"cake":"เค้ก",
	"chair":"เก้าอี้",
	"couch":"โซฟา",
	"potted plant":"ไม้กระถาง",
	"bed":"เตียง",
	"???":"-",
	"dining table":"โต๊ะรับประทานอาหาร",
	"???":"-",
	"???":"-",
	"toilet":"ห้องน้ำ",
	"???":"-",
	"tv":"โทรทัศน์",
	"laptop":"แล็ปท็อป",
	"mouse":"หนู",
	"remote":"ระยะไกล",
	"keyboard":"แป้นพิมพ์",
	"cell phone":"โทรศัพท์มือถือ",
	"microwave":"ไมโครเวฟ",
	"oven":"เตาอบ",
	"toaster":"เครื่องปิ้งขนมปัง",
	"sink":"จม",
	"refrigerator":"ตู้เย็น",
	"???":"-",
	"book":"หนังสือ",
	"clock":"นาฬิกา",
	"vase":"แจกัน",
	"scissors":"กรรไกร",
	"teddy bear":"หมีเท็ดดี้",
	"hair drier":"เครื่องเป่าผม",
	"toothbrush":"แปรงสีฟัน	"}
def thlabel(text):
    if labelall[text]:
        return labelall[text]
    else:
        return text
